name: Alert parent repository on push
on: push
  
jobs:
  build:
    name: Dispatch to `jarusll.github.io`
    runs-on: ubuntu-latest
    steps:
      # - name: Print secret REPO_ACCESS_TOKEN
      #   run: |
      #     echo "$TOKEN"
      #   shell: bash
      #   env:
      #     TOKEN: ${{secrets.REPO_ACCESS_TOKEN}}
      - name: Dispatch workflow_dispatch event
        uses: ph-fritsche/action-dispatch@v1
        with:
          token: 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
          ident: diary_push
