name: Alert parent repository on push
on: push
  
jobs:
  build:
    name: Dispatch to `jarusll.github.io`
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch workflow_dispatch event
        uses: ph-fritsche/action-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ident: diary_push
