name: Alert parent repository on push

on:
  workflow_dispatch:
  push:
    branches:    
      - main
  
jobs:
  build:
    name: Dispatch to `jarusll.github.io`
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@main
        with:
          token: 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
          repo: jarusll.github.io
          owner: jarusll
          event_type: diary_push
